language: go
go:
    - 1.16.3
env:
    - GO111MODULE=on
install:
#    - go get
before_deploy:
    make build-all
deploy:
    provider: release
    api_key: $GH_TOKEN
    file_glob: true
    file: bin/*
    skip_cleanup: true
    on:
        repo: bottxiang/hobby
        tags: true
